### ISSUE TITLE
"Too many parameters" error on Windows

### ISSUE THREAD

**Issue by dchekanov** [MrRaindrop/tree-cli#1]
It doesn't seem to accept parameters when running on Windows:

`> tree -L 2 -o out.txt`
`Too many parameters - 2`

`> tree -o tree.txt`
`Too many parameters - tree.txt`

**Comment by MrRaindrop** [comment]
It's the system's `tree` command, not of this package. In the latest version (0.4.9) of `tree-cli`, there's a alias command for `tree` to use, the `treee`. Just enter the command `treee -l 2 -o out.txt` and it should work fine.

**Comment by Alireza-shahbaziyan** [comment]
The `tree` command on Windows 11 doesn't support the `-I` flag — that's a Linux/macOS option. Windows has its own built-in `tree` command with very limited filtering options.

Here are your best alternatives:

## Option 1: Use PowerShell (built-in, no install needed)

```powershell
Get-ChildItem -Recurse | Where-Object { $_.FullName -notmatch 'node_modules|\.git|dist' } | Select-Object FullName
```

Or for a cleaner tree-like output:

```powershell
Get-ChildItem -Recurse -Exclude node_modules | Where-Object { $_.FullName -notmatch '\\node_modules\\|\\\.git\\|\\dist\\' }
```
