### ISSUE TITLE
The directory named "module" is missing

### ISSUE THREAD

**Issue by Euiyeon** [MrRaindrop/tree-cli#14]
### source directory structure

```plain
...
|-- build
|  |-- main
|  |-- module
...
```

### tree-cli result

```sh
tree -l 2 -o tree.txt --ignore 'node_modules,coverage'
```

![](https://i.imgur.com/OEpvsRy.png)

`build/module` directory is missing from the results.

**Comment by MrRaindrop** [comment]
@Euiyeon can u provide a github repository for me to debug it? It looks like the type of the file or directory is  considered invalid to show in the result list.

**Comment by Euiyeon** [comment]
<https://github.com/Euiyeon/tree-cli-debug>
There seems to be a problem with the string parsing of the ignore option.
