### ISSUE TITLE
Debug log is printed by default

### ISSUE THREAD

**Issue by danfooo** [MrRaindrop/tree-cli#4]
When I `tree ./build`, I get my log prepended by this:

```
[log] flags { debug: false,
  base: '.',
  indent: 2,
  fullpath: false,
  link: false,
  noreport: false,
  l: 1,
  o: 'tree_out',
  f: false }
[log] result:
```

I'd expect that not to be there when I'm not passing any debug flags.
My version of `tree` is `0.4.6`, node version is `6.7.0`.

**Comment by MrRaindrop** [comment]
You are right, now it's concealed for the `--debug` flag, just to print the result and output file path.

**Comment by danfooo** [comment]
Okay yeah, looks better in `0.4.9`. Another problem is that by default a `tree_out` file is written, that's not supposed to happen, right?
