### ISSUE TITLE
```tree -l 2 -o out.txt -d``` throws error on Windows 7

### ISSUE THREAD

**Issue by tylerlindell** [MrRaindrop/tree-cli#7]
error message is this: ```tree -l 2 -o out.txt -d```

**Comment by MrRaindrop** [comment]
Just try this:
```shell
treee -l 2 -o out.txt -d
```

**Note the `tree` command should be replaced by `treee`** since the `tree` command has already been taken by windows system.
There's another bug for `-d`, which is fixed in the newest version 0.4.12.
