### ISSUE TITLE
Available to be used as npm module

### ISSUE THREAD

**Issue by keyboard-clacker** [MrRaindrop/tree-cli#9]
Are there any plans to make this available to use as a `require`-able node module? I'm looking for something similar to this for one of my projects and it'd be pretty awesome to be able to use in another node script :)

**Comment by MrRaindrop** [comment]
I think this idea is definitely a good idea ! I'll make this require-able when I have time to do the work... May be in this weekend. Thx for your feedback !

**Comment by yangshun** [comment]
@kyleholzinger Check out a similar package that I wrote to solve this pain point - https://github.com/yangshun/tree-node-cli

**Comment by kyleholzinger** [comment]
Nice @yangshun ! Thanks!!

**Comment by MrRaindrop** [comment]
I've added the export function to return a promise with tree data and also export the d.ts in the package in the last publish version 5.0.1
